.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH csadduser 1 "Abril 30, 2014" "" "csadduser"

.SH NOMBRE
csadduser \- Un sencillo script para añadir usuarios al sistema local con su correspondiente configuración.

.SH SINOPSIS
.B csadduser
.RI [ opciones ]
.br

.SH DESCRIPCION
El programa
.B csadduser
se encarga de añadir y configurar la carpeta personal del usuario, el tiempo de expiración y su quota de disco en el sistema, además añade el usuario en Samba.
.PP

.SH OPCIONES
.B
.IP <user>::
Nombre del usuario a añadir en el sistema

.SH "SEE ALSO"
csdeluser