.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH csdeluser 1 "Abril 30, 2014" "" "csdeluser"

.SH NOMBRE
csdeluser \- Un sencillo script para añadir usuarios al sistema local con su correspondiente configuración.

.SH SINOPSIS
.B csdeluser
.RI [ opciones ]
.br

.SH DESCRIPCION
El programa
.B csdeluser
se encarga de eliminar el usuario local junto con la configuración personal, usuario de samba, etc.
.PP

.SH OPCIONES
.B
.IP <user>::
Nombre del usuario a eliminar en el sistema

.SH "SEE ALSO"
csdeluser